name: NodeJS with Webpack

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      targetZip: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install && \
        npm run-script build && \
        ls
        
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: "dist"
        filename: "${{ env.targetZip }}"
        
    - run: mkdir -pv testing && echo 123 > testing/testing.txt
    
    - name: Deploy to web server
      uses: moonpathbg/scp_uploader@latest
      with:
          host: ec2-43-198-50-165.ap-east-1.compute.amazonaws.com
          port: 22
          username: ubuntu
          key : ${{ secrets.SSH_KEY }}
          source: "./testing/*"
          target: "/var/www/html/testing"
        
    - name: Release prebuilt
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/${{ env.targetZip }}"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
