name: NodeJS with Webpack

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      hostName: ubuntu@ec2-43-198-151-195.ap-east-1.compute.amazonaws.com
      targetFolder: /home/ubuntu/public
      targetZip: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install && \
        npm run-script build && \
        ls

    # - run: |
    #     curl https://the.earth.li/~sgtatham/putty/latest/w64/putty.zip -L -O &&^
    #     7z.exe x putty.zip
    
    - run: |
        sudo rm /var/lib/apt/lists/lock && \
        sudo add-apt-repository universe && \
        sudo apt-get update -y && \
        sudo apt-get upgrade -y && \
        sudo apt-get -y --no-install-recommends install \
        zip \
        unzip \
        putty

    - run: plink --version
    
    - run: pscp --version
    
    - run: |
        echo "${{ secrets.SSH_PPK_KEY_CONTENT }}" > alex.ppk && \
        ls && \
        echo y | plink -i alex.ppk -no-antispoof -ssh "${{ env.hostName }}" "rm -rf ${{ env.targetFolder }}/*" && \
        echo y | pscp -i alex.ppk -r "./dist/" "${{ env.hostName }}:${{ env.targetFolder }}/"
      
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: "dist"
        filename: "${{ env.targetZip }}"
        
    - name: Release prebuilt
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/${{ env.targetZip }}"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
